* 关于中行考试的建议
基本流程：报名、筛选简历、准备笔试、笔试、公布成绩、准备面试、面试、公布成绩、
体检、签约。

** 面试试题
总体来说，面试分成两个大部分，无领导小组，半结构化。[fn:0]

[fn:0] 请不要嫌弃这后面的话罗嗦，这些都是通用的建议，也就是说，即使你准备其它公司
的面试（尤其是大厂），都有一些八股文，不信请看 *Leetcode* 上的面试小作文，都很繁琐。

*** 无领导小组
可以理解为一种以四五个人为小团体的面试，考察重点在仪表、谈吐、合作、领导力、知识。

**** 大概的形式[fn:1]
会给你一段材料，然后各自陈述观点。之后，会有小组讨论，要求得出
一致的结论，并选出一个代表，陈述讨论得出的结果。整个小组讨论大概持续 3 ～ 5 分钟。
最后的陈述大概 1 分钟。
[fn:1] 如果你参加过类似的面试，这一段可以忽略，直接看题目。

**** 参考案例
1. 一段关于清明祭祖的材料，问：你的观点。

2. 一段关于偏远地区人才引进的材料，问：你的观点


*** 半结构化面试
简单地说，就是面试官问，你来回答。重点在你的个人表现，没有小组讨论。面试的最后，你
有机会向面试官问问题。一般来说，会有 *两次* 面试。

在半结构化面试，个人陈述要简洁，要在 *三分钟* 内作完个人陈述。

**** 个人介绍
*个人介绍* 是一定会有的，可以提前准备下，可以夸张，但不能作假。[fn:2] 至少包含以下信息。
    * 个人信息，e.g. 考号、学校、面试岗位；
    * 教育背景，e.g. 专业、成就、所学方向；
    * 社会实践，e.g. 志愿者经历，社团经历；
    * 工作经历  e.g. 公司名称、职位、职责、业绩、个人能力体现在哪、兴趣；
    * 为什么要面试中行？

[fn:2] 面试官面前会有你的个人简历，其中包含了你在报名时所填写的个人信息，这个简历
可以自己保留一份，以备准备个人介绍时用。

**** 参考案例
   * 职业规划、理想的工作环境、关于柜员的职业修养；
   * 学校经历、最有挑战性的事，你的专业可以为银行做什么；


** 关于笔试
整体来说，如果你报名柜员岗位，那么笔试会有三个部分，英语、行测、专业
考试时间一般为 140 分钟。[fn:3] 在这三部分中，行测是最重要的。建议重点学习
“逻辑推理”与“数学运算”。
专业知识会很繁杂，都要熟悉。英语要正确率稳定。

[fn:3] 不必担心时间，考试内容都是选择题，每个部分的时间是固定的，也就是说，
你不可以在规定时间外回溯上一部分的题目，所以通常我们都是用完每一部分的规定时间。

** 关于备考
如果你准备过公务员考试，中行的考试题目与之相似，准备方法也相似，你可以关闭这个
页面。如果你不知道行测是什么，那么请继续阅读。

整体来说，中行秋季招聘目前没有开通，根据去年的经验，中行应该会在9月发布消息，
最晚10月截至报名。如果你想参加中行的秋季招聘考试，需要现在开始准备。[fn:4]

如果想自学，建议关注[[https://m.weibo.cn/p/index?extparam=中国银行&containerid=100808d777a959d197b1ffaffceec29ddab909&luicode=10000011&lfid=100103type%3D1%26q%3D中国银行超话][中行超话]]，其中有许多有用的提问。我只建议报名面试的课程，最好
是线下课程，网课也行。笔试的话，建议先买本[[https://item.jd.com/45111052380.html][教材]]先看看，重点看行测，网上的视频大多
路子不对，慎重挑选。如果看不懂，如果去辅导班，华图、中公区别不大，别的小辅导班，
那就更看运气了。


[fn:4] 至少提前三个月准备考试。
